// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Net;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShareFile.Api.Client.Extensions;
using ShareFile.Api.Client.Exceptions;

namespace ShareFile.Api.Client.Models 
{
	/// <summary>
	/// User Activation Token
	/// </summary>
	public class ActivationToken : ODataObject 
	{
		public string Token { get; set; }

		public override void Copy(ODataObject source, JsonSerializer serializer)
		{
			if(source == null || serializer == null) return;
			base.Copy(source, serializer);

			var typedSource = source as ActivationToken;
			if(typedSource != null)
			{
				Token = typedSource.Token;
			}
			else
			{
				JToken token;
				if(source.TryGetProperty("Token", out token) && token.Type != JTokenType.Null)
				{
					Token = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
			}
		}
	}
}