// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace ShareFile.Api.Client.Models 
{
    
    /// <summary>
    /// Async Operation state
    /// </summary>
    public enum AsyncOperationState
    {
        Created = 0,
        Scheduled = 1,
        Success = 2,
        Failure = 3,
        Canceled = 4
    }
}
