// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Net;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShareFile.Api.Client.Extensions;
using ShareFile.Api.Client.Exceptions;

namespace ShareFile.Api.Client.Models 
{
	/// <summary>
	/// The current usage statistics for DiskSpace on the Account
	/// </summary>
	public class DiskSpace : ODataObject 
	{
		/// <summary>
		/// Max space allowed
		/// </summary>
		public int? Max { get; set; }
		/// <summary>
		/// Current space used
		/// </summary>
		public int? Used { get; set; }
		/// <summary>
		/// Current space free
		/// </summary>
		public int? Free { get; set; }

		public override void Copy(ODataObject source, JsonSerializer serializer)
		{
			if(source == null || serializer == null) return;
			base.Copy(source, serializer);

			var typedSource = source as DiskSpace;
			if(typedSource != null)
			{
				Max = typedSource.Max;
				Used = typedSource.Used;
				Free = typedSource.Free;
			}
			else
			{
				JToken token;
				if(source.TryGetProperty("Max", out token) && token.Type != JTokenType.Null)
				{
					Max = (int?)serializer.Deserialize(token.CreateReader(), typeof(int?));
				}
				if(source.TryGetProperty("Used", out token) && token.Type != JTokenType.Null)
				{
					Used = (int?)serializer.Deserialize(token.CreateReader(), typeof(int?));
				}
				if(source.TryGetProperty("Free", out token) && token.Type != JTokenType.Null)
				{
					Free = (int?)serializer.Deserialize(token.CreateReader(), typeof(int?));
				}
			}
		}
	}
}