// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace ShareFile.Api.Client.Models 
{
    
    /// <summary>
    /// Enumeration for Virus Scan status of an Item.
    /// </summary>
    public enum FileVirusStatus
    {
        
        /// <summary>
        /// File was scanned and an A/V warning was received
        /// </summary>
        VirusWarning = -1,
        
        /// <summary>
        /// File has not been scanned yet
        /// </summary>
        NotScanned = 0,
        
        /// <summary>
        /// File was scanned and no viruses were found
        /// </summary>
        Clean = 1
    }
}
