// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace ShareFile.Api.Client.Models 
{
    public enum FolderOption
    {
        ForcedSort = 0,
        ForcedThumbnails = 1,
        EnableDisplayInline = 2,
        EnableDocViewerPrinting = 3,
        ViewOnlyWatermarkText = 4,
        IsVersioned = 5,
        EnableWatermarkedDownloads = 6,
        MaxVersions = 7
    }
}
