// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Net;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShareFile.Api.Client.Extensions;
using ShareFile.Api.Client.Exceptions;

namespace ShareFile.Api.Client.Models 
{
	/// <summary>
	/// InboxMetadata contains metadata of the inbox for a user.
	/// </summary>
	public class InboxMetadata : ODataObject 
	{
		public int UnreadSendUnarchived { get; set; }
		public int UnreadRequestUnarchived { get; set; }

		public override void Copy(ODataObject source, JsonSerializer serializer)
		{
			if(source == null || serializer == null) return;
			base.Copy(source, serializer);

			var typedSource = source as InboxMetadata;
			if(typedSource != null)
			{
				UnreadSendUnarchived = typedSource.UnreadSendUnarchived;
				UnreadRequestUnarchived = typedSource.UnreadRequestUnarchived;
			}
			else
			{
				JToken token;
				if(source.TryGetProperty("UnreadSendUnarchived", out token) && token.Type != JTokenType.Null)
				{
					UnreadSendUnarchived = (int)serializer.Deserialize(token.CreateReader(), typeof(int));
				}
				if(source.TryGetProperty("UnreadRequestUnarchived", out token) && token.Type != JTokenType.Null)
				{
					UnreadRequestUnarchived = (int)serializer.Deserialize(token.CreateReader(), typeof(int));
				}
			}
		}
	}
}