// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace ShareFile.Api.Client.Models 
{
    public enum ReportRunFrequency
    {
        Once = 0,
        Daily = 1,
        Weekly = 2,
        Monthly = 3
    }
}
