// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace ShareFile.Api.Client.Models 
{
    public enum SFTool
    {
        DriveMapping = 1,
        EnterpriseSync = 2,
        FTP = 4,
        Outlook = 8,
        SFCLI = 16,
        SFTP = 32,
        SMTP = 64,
        Sync = 128,
        WebDAV = 256,
        Widget = 512,
        AndroidPhone = 536870913,
        AndroidTablet = 536870914,
        BlackberryPhone = 536870915,
        BlackberryTablet = 536870916,
        iPhone = 536870917,
        iPad = 536870918,
        ReceiverAndroid = 536870919,
        ReceiveriOS = 536870920,
        ReceiverMac = 536870921,
        ReceiverWindows = 536870922,
        WindowsPhone = 536870923,
        Unknown = 536870924
    }
}
