// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Net;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShareFile.Api.Client.Extensions;
using ShareFile.Api.Client.Exceptions;

namespace ShareFile.Api.Client.Models 
{
	/// <summary>
	/// SendShareParams
	/// </summary>
	public class ShareSendParams : ODataObject 
	{
		/// <summary>
		/// List of Item Ids to be sent
		/// </summary>
		public IEnumerable<string> Items { get; set; }
		/// <summary>
		/// List of emails to whom this Share should be sent
		/// </summary>
		public IEnumerable<string> Emails { get; set; }
		/// <summary>
		/// The subject of the Share email
		/// </summary>
		public string Subject { get; set; }
		/// <summary>
		/// A message to be included in the Share email body
		/// </summary>
		public string Body { get; set; }
		/// <summary>
		/// If true, the Share sender will be cc'd in the Share email
		/// </summary>
		public bool CcSender { get; set; }
		/// <summary>
		/// If true, recipients will need to login to access the Share
		/// </summary>
		public bool RequireLogin { get; set; }
		/// <summary>
		/// If true, anyone with the link can access the Share. Cannot be true if RequireLogin is true
		/// </summary>
		public bool SendAnon { get; set; }
		/// <summary>
		/// If true, a recipient will need to provide their full name and email to access the Share. Cannot be true if RequireLogin is true
		/// </summary>
		public bool RequireUserInfo { get; set; }
		/// <summary>
		/// Number of days until access to this Share expires
		/// </summary>
		public int ExpirationDays { get; set; }
		/// <summary>
		/// If true, the sender will receive an email notification when the Share items are downloaded
		/// </summary>
		public bool NotifyOnDownload { get; set; }
		/// <summary>
		/// If true, the Share items can only be viewed but not downloaded. Requires account preference EnableViewOnly to work
		/// </summary>
		public bool IsViewOnly { get; set; }
		/// <summary>
		/// Maximum number of times each recipient can download the Share items
		/// </summary>
		public int MaxDownloads { get; set; }
		/// <summary>
		/// When enabled the items are identified by stream IDs instead of item IDs.
		/// Applies to Send Shares only. (FINRA enabled accounts cannot use this)
		/// </summary>
		public bool? UsesStreamIDs { get; set; }
		/// <summary>
		/// Used to define the share type and share action types
		/// </summary>
		public ShareAccessRight ShareAccessRight { get; set; }

		public override void Copy(ODataObject source, JsonSerializer serializer)
		{
			if(source == null || serializer == null) return;
			base.Copy(source, serializer);

			var typedSource = source as ShareSendParams;
			if(typedSource != null)
			{
				Items = typedSource.Items;
				Emails = typedSource.Emails;
				Subject = typedSource.Subject;
				Body = typedSource.Body;
				CcSender = typedSource.CcSender;
				RequireLogin = typedSource.RequireLogin;
				SendAnon = typedSource.SendAnon;
				RequireUserInfo = typedSource.RequireUserInfo;
				ExpirationDays = typedSource.ExpirationDays;
				NotifyOnDownload = typedSource.NotifyOnDownload;
				IsViewOnly = typedSource.IsViewOnly;
				MaxDownloads = typedSource.MaxDownloads;
				UsesStreamIDs = typedSource.UsesStreamIDs;
				ShareAccessRight = typedSource.ShareAccessRight;
			}
			else
			{
				JToken token;
				if(source.TryGetProperty("Items", out token) && token.Type != JTokenType.Null)
				{
					Items = (IEnumerable<string>)serializer.Deserialize(token.CreateReader(), typeof(IEnumerable<string>));
				}
				if(source.TryGetProperty("Emails", out token) && token.Type != JTokenType.Null)
				{
					Emails = (IEnumerable<string>)serializer.Deserialize(token.CreateReader(), typeof(IEnumerable<string>));
				}
				if(source.TryGetProperty("Subject", out token) && token.Type != JTokenType.Null)
				{
					Subject = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("Body", out token) && token.Type != JTokenType.Null)
				{
					Body = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("CcSender", out token) && token.Type != JTokenType.Null)
				{
					CcSender = (bool)serializer.Deserialize(token.CreateReader(), typeof(bool));
				}
				if(source.TryGetProperty("RequireLogin", out token) && token.Type != JTokenType.Null)
				{
					RequireLogin = (bool)serializer.Deserialize(token.CreateReader(), typeof(bool));
				}
				if(source.TryGetProperty("SendAnon", out token) && token.Type != JTokenType.Null)
				{
					SendAnon = (bool)serializer.Deserialize(token.CreateReader(), typeof(bool));
				}
				if(source.TryGetProperty("RequireUserInfo", out token) && token.Type != JTokenType.Null)
				{
					RequireUserInfo = (bool)serializer.Deserialize(token.CreateReader(), typeof(bool));
				}
				if(source.TryGetProperty("ExpirationDays", out token) && token.Type != JTokenType.Null)
				{
					ExpirationDays = (int)serializer.Deserialize(token.CreateReader(), typeof(int));
				}
				if(source.TryGetProperty("NotifyOnDownload", out token) && token.Type != JTokenType.Null)
				{
					NotifyOnDownload = (bool)serializer.Deserialize(token.CreateReader(), typeof(bool));
				}
				if(source.TryGetProperty("IsViewOnly", out token) && token.Type != JTokenType.Null)
				{
					IsViewOnly = (bool)serializer.Deserialize(token.CreateReader(), typeof(bool));
				}
				if(source.TryGetProperty("MaxDownloads", out token) && token.Type != JTokenType.Null)
				{
					MaxDownloads = (int)serializer.Deserialize(token.CreateReader(), typeof(int));
				}
				if(source.TryGetProperty("UsesStreamIDs", out token) && token.Type != JTokenType.Null)
				{
					UsesStreamIDs = (bool?)serializer.Deserialize(token.CreateReader(), typeof(bool?));
				}
				if(source.TryGetProperty("ShareAccessRight", out token) && token.Type != JTokenType.Null)
				{
					ShareAccessRight = (ShareAccessRight)serializer.Deserialize(token.CreateReader(), typeof(ShareAccessRight));
				}
			}
		}
	}
}