// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Net;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShareFile.Api.Client.Extensions;
using ShareFile.Api.Client.Exceptions;

namespace ShareFile.Api.Client.Models 
{
	/// <summary>
	/// Represents the settings applicable to a Storage Category Policy definition for use within ShareFile's Policy Based Administration
	/// </summary>
	public class StorageSettings : ODataObject 
	{
		public string StorageZoneId { get; set; }

		public override void Copy(ODataObject source, JsonSerializer serializer)
		{
			if(source == null || serializer == null) return;
			base.Copy(source, serializer);

			var typedSource = source as StorageSettings;
			if(typedSource != null)
			{
				StorageZoneId = typedSource.StorageZoneId;
			}
			else
			{
				JToken token;
				if(source.TryGetProperty("StorageZoneId", out token) && token.Type != JTokenType.Null)
				{
					StorageZoneId = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
			}
		}
	}
}