// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Net;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShareFile.Api.Client.Extensions;
using ShareFile.Api.Client.Exceptions;

namespace ShareFile.Api.Client.Models 
{
	/// <summary>
	/// The event type a subscription will process
	/// </summary>
	public class SubscribedResourceEvent : ODataObject 
	{
		/// <summary>
		/// The Event Resource Type
		/// </summary>
		public string ResourceType { get; set; }
		/// <summary>
		/// The Event Operation Name
		/// </summary>
		public string OperationName { get; set; }

		public override void Copy(ODataObject source, JsonSerializer serializer)
		{
			if(source == null || serializer == null) return;
			base.Copy(source, serializer);

			var typedSource = source as SubscribedResourceEvent;
			if(typedSource != null)
			{
				ResourceType = typedSource.ResourceType;
				OperationName = typedSource.OperationName;
			}
			else
			{
				JToken token;
				if(source.TryGetProperty("ResourceType", out token) && token.Type != JTokenType.Null)
				{
					ResourceType = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("OperationName", out token) && token.Type != JTokenType.Null)
				{
					OperationName = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
			}
		}
	}
}