// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Net;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShareFile.Api.Client.Extensions;
using ShareFile.Api.Client.Exceptions;

namespace ShareFile.Api.Client.Models 
{
	/// <summary>
	/// User Bulk Downgrade Request
	/// </summary>
	public class UserBulkDowngradeRequest : UserBulkOperationRequest 
	{
		/// <summary>
		/// If provided, all users in this bulk operation have their items reassigned to this user id
		/// </summary>
		public string ReassignItemsToId { get; set; }
		/// <summary>
		/// If provided, all users in this bulk operation have their groups reassigned to this user id
		/// </summary>
		public string ReassignGroupsToId { get; set; }

		public override void Copy(ODataObject source, JsonSerializer serializer)
		{
			if(source == null || serializer == null) return;
			base.Copy(source, serializer);

			var typedSource = source as UserBulkDowngradeRequest;
			if(typedSource != null)
			{
				ReassignItemsToId = typedSource.ReassignItemsToId;
				ReassignGroupsToId = typedSource.ReassignGroupsToId;
			}
			else
			{
				JToken token;
				if(source.TryGetProperty("ReassignItemsToId", out token) && token.Type != JTokenType.Null)
				{
					ReassignItemsToId = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("ReassignGroupsToId", out token) && token.Type != JTokenType.Null)
				{
					ReassignGroupsToId = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
			}
		}
	}
}