// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace ShareFile.Api.Client.Models 
{
    
    /// <summary>
    /// User Roles
    /// </summary>
    public enum UserRole
    {
        Client = 1,
        Employee = 2,
        MasterAdmin = 3,
        SuperUser = 4,
        CanChangePassword = 10,
        CanManageMySettings = 11,
        CanUseFileBox = 30,
        CanManageUsers = 31,
        CanCreateFolders = 32,
        CanUseDropBox = 33,
        CanSelectFolderZone = 34,
        CreateNetworkShareConnectors = 35,
        CreateSharePointConnectors = 36,
        CreateSharePointOnlineConnectors = 37,
        CreateOneDriveConnectors = 38,
        CreateExchangeConnectors = 39,
        CreateBoxConnectors = 40,
        CreateDropboxConnectors = 41,
        CreateGoogleDriveConnectors = 42,
        CreateOneDriveBusinessConnectors = 43,
        CanSendDocumentsForSignature = 44,
        CanViewSignatureDocuments = 45,
        CanManageSignatureTemplates = 46,
        AdminAccountPolicies = 50,
        AdminBilling = 51,
        AdminBranding = 52,
        AdminChangeFolderPay = 53,
        AdminChangePlan = 54,
        AdminFileBoxAccess = 55,
        AdminManageEmployees = 56,
        AdminRemoteUploadForms = 57,
        AdminReporting = 58,
        AdminSharedDistGroups = 59,
        AdminSharedAddressBook = 60,
        AdminViewVdrAnalytics = 61,
        AdminViewReceipts = 62,
        AdminDelegate = 63,
        AdminManageDropBox = 64,
        AdminManageFolderTemplates = 65,
        AdminEmailMessages = 66,
        AdminSSO = 67,
        AdminSuperGroup = 68,
        AdminZones = 69,
        AdminCreateSharedGroups = 70,
        AdminArchivedSearch = 71,
        AdminConnectors = 72,
        AdminEmailArchiver = 73,
        AdminCanAdministerCustomerAccount = 74,
        AdminPolicyDefinitions = 75,
        AdminCustomWorkflow = 76
    }
}
