// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//	   Copyright (c) 2018 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace ShareFile.Api.Client.Models 
{
    public enum VRootType
    {
        Account = 0,
        Virtual = 1,
        ForcedVirtual = 2,
        ClassicVirtual = 3,
        ForcedClassicVirtual = 4,
        Home = 5,
        ForcedDefault = 254,
        Default = 255
    }
}
