// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using ShareFile.Api.Models;
using ShareFile.Api.Client;

namespace ShareFile.Api.Client
{
#if ShareFile
	public class ItemsEntityInternal : ItemsEntity
	{
		/// <summary>
		/// Advanced Simple Search
		/// </summary>
		/// <example>
		/// {
		/// "Query":{
		/// "AuthID":"",
		/// "ItemType":"",
		/// "ParentID":"",
		/// "CreatorID":"",
		/// "LuceneQuery":"",
		/// "SearchQuery":"",
		/// "CreateStartDate":"",
		/// "CreateEndDate":"",
		/// "ItemNameOnly":"",
		/// },
		/// "Paging":{
		/// "Key":"",
		/// "PageNumber":1,
		/// "PageSize":10,
		/// },
		/// "Sort":{
		/// "SortBy":"",
		/// "Ascending":false,
		/// },
		/// "TimeoutInSeconds":10
		/// }
		/// </example>
		/// <remarks>
		/// Search for Items matching the criteria of the query parameter
		/// </remarks>
		/// <param name="simpleSearchQuery"></param>
		/// <returns>
		/// AdvancedSearchResults
		/// </returns>
		public IQuery<AdvancedSearchResults> AdvancedSimpleSearch(SimpleSearchQuery simpleSearchQuery)
		{
			IQuery<AdvancedSearchResults> query = new IQuery<AdvancedSearchResults>(Client);
			query.From("Items");
			query.Action("AdvancedSimpleSearch");
			query.Body = simpleSearchQuery;
			query.HttpMethod = "POST";
			return query;
		}

		/// <summary>
		/// Advanced Search
		/// </summary>
		/// <example>
		/// {
		/// "Query":{
		/// "AuthIDs":["id1", "id2", ...],
		/// "ItemTypes":["type1", "type2", ...],
		/// "ParentID":["id1", "id2", ...],
		/// "CreatorID":["id1", "id2", ...],
		/// "LuceneQuery":"",
		/// "SearchQuery":"",
		/// "CreateStartDate":"",
		/// "CreateEndDate":"",
		/// "ItemNameOnly":"",
		/// },
		/// "Paging":{
		/// "Key":"",
		/// "PageNumber":1,
		/// "PageSize":10,
		/// },
		/// "Sort":{
		/// "SortBy":"",
		/// "Ascending":false,
		/// },
		/// "TimeoutInSeconds":10
		/// }
		/// </example>
		/// <remarks>
		/// Search for Items matching the criteria of the query parameter
		/// </remarks>
		/// <param name="searchQuery"></param>
		/// <returns>
		/// AdvancedSearchResults
		/// </returns>
		public IQuery<AdvancedSearchResults> AdvancedSearch(SearchQuery searchQuery)
		{
			IQuery<AdvancedSearchResults> query = new IQuery<AdvancedSearchResults>(Client);
			query.From("Items");
			query.Action("AdvancedSimpleSearch");
			query.Body = searchQuery;
			query.HttpMethod = "POST";
			return query;
		}

	}
#endif
}
