// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using ShareFile.Api.Models;
using ShareFile.Api.Client;

namespace ShareFile.Api.Client
{
#if ShareFile
	public class UsersEntityInternal : UsersEntity
	{
		/// <summary>
		/// Get User Security
		/// </summary>
		/// <remarks>
		/// Retrieve the user security record - current state of the user regarding
		/// security and password settings.
		/// </remarks>
		/// <param name="id"></param>
		/// <returns>
		/// the user security status
		/// </returns>
		public IQuery<UserSecurity> GetSecurity(string id)
		{
			IQuery<UserSecurity> query = new IQuery<UserSecurity>(Client);
			query.From("Users");
			query.Action("Security");
			query.Ids(id);
			query.HttpMethod = "GET";
			return query;
		}

	}
#endif
}
