// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ShareFile.Api.Models 
{
	public class MobileSecuritySettings : ODataObject 
	{
		public int PoisonPillInterval { get; set; }

		public bool? EnableOpenExternal { get; set; }

		public bool? EnableOfflineCache { get; set; }

		public bool? EnableAutoLogin { get; set; }

		public bool? RestrictModifiedDevices { get; set; }

		public PinLockType? PinLockType { get; set; }

	}
}