// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyProductAttribute("ShareFile.Api.Client")]
[assembly: AssemblyTitleAttribute("ShareFile Client SDK")]
[assembly: AssemblyVersionAttribute("4.0.0")]
[assembly: AssemblyFileVersionAttribute("4.0.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © Citrix ShareFile 2016")]

[assembly: InternalsVisibleTo("ShareFile.Api.Client.Tests")]
