// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace ShareFile.Api.Models 
{
#if ShareFile
	public enum AddonField
    {
        Employees = 0,
        StorageGB = 1,
        BandwidthGB = 2
    }
#endif
}