// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2015 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShareFile.Api.Client.Extensions;

namespace ShareFile.Api.Models 
{
#if ShareFile
	public class DlpPolicy : ODataObject 
	{

		public string Name { get; set; }

		public SafeEnum<DlpStatus> Status { get; set; }

		public bool? AnonymousUserCanDownload { get; set; }

		public bool? ClientUserCanDownload { get; set; }

		public bool? ClientUserCanShare { get; set; }

		public bool? EmployeeUserCanDownload { get; set; }

		public bool? EmployeeUserCanShare { get; set; }

		public override void Copy(ODataObject source, JsonSerializer serializer)
		{
			if(source == null || serializer == null) return;
			base.Copy(source, serializer);

			var typedSource = source as DlpPolicy;
			if(typedSource != null)
			{
				Name = typedSource.Name;
				Status = typedSource.Status;
				AnonymousUserCanDownload = typedSource.AnonymousUserCanDownload;
				ClientUserCanDownload = typedSource.ClientUserCanDownload;
				ClientUserCanShare = typedSource.ClientUserCanShare;
				EmployeeUserCanDownload = typedSource.EmployeeUserCanDownload;
				EmployeeUserCanShare = typedSource.EmployeeUserCanShare;
			}
			else
			{
				JToken token;
				if(source.TryGetProperty("Name", out token) && token.Type != JTokenType.Null)
				{
					Name = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("Status", out token) && token.Type != JTokenType.Null)
				{
					Status = (SafeEnum<DlpStatus>)serializer.Deserialize(token.CreateReader(), typeof(SafeEnum<DlpStatus>));
				}
				if(source.TryGetProperty("AnonymousUserCanDownload", out token) && token.Type != JTokenType.Null)
				{
					AnonymousUserCanDownload = (bool?)serializer.Deserialize(token.CreateReader(), typeof(bool?));
				}
				if(source.TryGetProperty("ClientUserCanDownload", out token) && token.Type != JTokenType.Null)
				{
					ClientUserCanDownload = (bool?)serializer.Deserialize(token.CreateReader(), typeof(bool?));
				}
				if(source.TryGetProperty("ClientUserCanShare", out token) && token.Type != JTokenType.Null)
				{
					ClientUserCanShare = (bool?)serializer.Deserialize(token.CreateReader(), typeof(bool?));
				}
				if(source.TryGetProperty("EmployeeUserCanDownload", out token) && token.Type != JTokenType.Null)
				{
					EmployeeUserCanDownload = (bool?)serializer.Deserialize(token.CreateReader(), typeof(bool?));
				}
				if(source.TryGetProperty("EmployeeUserCanShare", out token) && token.Type != JTokenType.Null)
				{
					EmployeeUserCanShare = (bool?)serializer.Deserialize(token.CreateReader(), typeof(bool?));
				}
			}
		}
	}
#endif
}