// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShareFile.Api.Client.Extensions;

namespace ShareFile.Api.Models 
{
	public class AzureSBTopicsEndPointInfo : ODataObject 
	{

		public string Key { get; set; }

		public string Secret { get; set; }

		public string EndPoint { get; set; }

		public override void Copy(ODataObject source, JsonSerializer serializer)
		{
			if(source == null || serializer == null) return;
			base.Copy(source, serializer);

			var typedSource = source as AzureSBTopicsEndPointInfo;
			if(typedSource != null)
			{
				Key = typedSource.Key;
				Secret = typedSource.Secret;
				EndPoint = typedSource.EndPoint;
			}
			else
			{
				JToken token;
				if(source.TryGetProperty("Key", out token) && token.Type != JTokenType.Null)
				{
					Key = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("Secret", out token) && token.Type != JTokenType.Null)
				{
					Secret = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("EndPoint", out token) && token.Type != JTokenType.Null)
				{
					EndPoint = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
			}
		}
	}
}