// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace ShareFile.Api.Models 
{
	public enum CapabilityName
    {
        Thumbnails = 0,
        DocPreview = 1,
        Search = 2,
        AdvancedSearch = 3,
        Sharing = 4,
        AnonymousSharing = 5,
        LastProgenyUpdateDate = 6,
        DirectDownload = 7,
        DirectUpload = 8,
        FileLocking = 9,
        FileVersioning = 10,
        RecycleBin = 11,
        FolderTemplates = 12,
        VirusScan = 13,
        ItemLink = 14,
        ItemNote = 15,
        CheckIn = 16,
        CheckOut = 17,
        ItemDescription = 18,
        VersionMax = 19,
        VersionMin = 20,
        Favorites = 21,
        ReusableItemId = 22,
        StandardUploadRaw = 23,
        StandardUploadForms = 24,
        StreamedUploadRaw = 25,
        StreamedUploadForms = 26,
        ThreadedUploadRaw = 27,
        ThreadedUploadForms = 28,
        RightSignature = 29
    }
}