// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace ShareFile.Api.Models 
{
	public enum FileVirusStatus
	{
		VirusWarning = -1,
		NotScanned = 0,
		Clean = 1
	}
}