// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShareFile.Api.Client.Extensions;

namespace ShareFile.Api.Models 
{
	public class FindSubdomainResult : ODataObject 
	{

		public string UserID { get; set; }

		public string Email { get; set; }

		public string AccountID { get; set; }

		public string CompanyName { get; set; }

		public string Subdomain { get; set; }

		public override void Copy(ODataObject source, JsonSerializer serializer)
		{
			if(source == null || serializer == null) return;
			base.Copy(source, serializer);

			if(source.GetType().IsSubclassOf(GetType()) || GetType() == source.GetType())
			{
				var typedSource = (FindSubdomainResult)source;
				UserID = typedSource.UserID;
				Email = typedSource.Email;
				AccountID = typedSource.AccountID;
				CompanyName = typedSource.CompanyName;
				Subdomain = typedSource.Subdomain;
			}
			else
			{
				JToken token;
				if(source.TryGetProperty("UserID", out token) && token.Type != JTokenType.Null)
				{
					UserID = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("Email", out token) && token.Type != JTokenType.Null)
				{
					Email = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("AccountID", out token) && token.Type != JTokenType.Null)
				{
					AccountID = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("CompanyName", out token) && token.Type != JTokenType.Null)
				{
					CompanyName = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("Subdomain", out token) && token.Type != JTokenType.Null)
				{
					Subdomain = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
			}
		}
	}
}