// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ShareFile.Api.Models 
{
	public class FindSubdomainResult : ODataObject 
	{

		public string UserID { get; set; }

		public string Email { get; set; }

		public string AccountID { get; set; }

		public string CompanyName { get; set; }

		public string Subdomain { get; set; }

	}
}