// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShareFile.Api.Client.Extensions;

namespace ShareFile.Api.Models 
{
	public class Query : ODataObject 
	{

		public IEnumerable<string> AuthIDs { get; set; }

		public IEnumerable<string> ItemTypes { get; set; }

		public IEnumerable<string> ParentID { get; set; }

		public IEnumerable<string> CreatorID { get; set; }

		public string LuceneQuery { get; set; }

		public string SearchQuery { get; set; }

		public string CreateStartDate { get; set; }

		public string CreateEndDate { get; set; }

		public bool ItemNameOnly { get; set; }

		public override void Copy(ODataObject source, JsonSerializer serializer)
		{
			if(source == null || serializer == null) return;
			base.Copy(source, serializer);

			if(source.GetType().IsSubclassOf(GetType()) || GetType() == source.GetType())
			{
				var typedSource = (Query)source;
				AuthIDs = typedSource.AuthIDs;
				ItemTypes = typedSource.ItemTypes;
				ParentID = typedSource.ParentID;
				CreatorID = typedSource.CreatorID;
				LuceneQuery = typedSource.LuceneQuery;
				SearchQuery = typedSource.SearchQuery;
				CreateStartDate = typedSource.CreateStartDate;
				CreateEndDate = typedSource.CreateEndDate;
				ItemNameOnly = typedSource.ItemNameOnly;
			}
			else
			{
				JToken token;
				if(source.TryGetProperty("AuthIDs", out token) && token.Type != JTokenType.Null)
				{
					AuthIDs = (IEnumerable<string>)serializer.Deserialize(token.CreateReader(), typeof(IEnumerable<string>));
				}
				if(source.TryGetProperty("ItemTypes", out token) && token.Type != JTokenType.Null)
				{
					ItemTypes = (IEnumerable<string>)serializer.Deserialize(token.CreateReader(), typeof(IEnumerable<string>));
				}
				if(source.TryGetProperty("ParentID", out token) && token.Type != JTokenType.Null)
				{
					ParentID = (IEnumerable<string>)serializer.Deserialize(token.CreateReader(), typeof(IEnumerable<string>));
				}
				if(source.TryGetProperty("CreatorID", out token) && token.Type != JTokenType.Null)
				{
					CreatorID = (IEnumerable<string>)serializer.Deserialize(token.CreateReader(), typeof(IEnumerable<string>));
				}
				if(source.TryGetProperty("LuceneQuery", out token) && token.Type != JTokenType.Null)
				{
					LuceneQuery = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("SearchQuery", out token) && token.Type != JTokenType.Null)
				{
					SearchQuery = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("CreateStartDate", out token) && token.Type != JTokenType.Null)
				{
					CreateStartDate = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("CreateEndDate", out token) && token.Type != JTokenType.Null)
				{
					CreateEndDate = (string)serializer.Deserialize(token.CreateReader(), typeof(string));
				}
				if(source.TryGetProperty("ItemNameOnly", out token) && token.Type != JTokenType.Null)
				{
					ItemNameOnly = (bool)serializer.Deserialize(token.CreateReader(), typeof(bool));
				}
			}
		}
	}
}