// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace ShareFile.Api.Models 
{
	public class FavoriteFolder : ODataObject 
	{
		public User User { get; set; }

		public Item Folder { get; set; }

		public int? SortOrder { get; set; }

		public string FolderAlias { get; set; }

		public string FolderName { get; set; }

		public string Path { get; set; }

		public long? FileSize { get; set; }

		public DateTime? CreationDate { get; set; }

		public string CreatorFirstName { get; set; }

		public string CreatorLastName { get; set; }

	}
}