// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace ShareFile.Api.Models 
{
	public class ODataFeed<T> : ODataObject 
	{
		[JsonProperty(PropertyName = "odata.count")] 
		public int count { get; set; }

		[JsonProperty(PropertyName = "value")] 
		public IEnumerable<T> Feed { get; set; }

		[JsonProperty(PropertyName = "odata.nextLink")] 
		public string NextLink { get; set; }

	}
}