// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2015 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using ShareFile.Api.Models;
using ShareFile.Api.Client;
using ShareFile.Api.Client.Requests;
using ShareFile.Api.Client.Extensions;

namespace ShareFile.Api.Client.Entities.Extensions
{
    public static class FolderTemplatesEntityInternalExtensions
    {
        public static IQuery<AsyncOperation> BulkApply(this IFolderTemplatesEntity entity, Uri url, string folderId, int batchSize = -1)
        {
            var sfApiQuery = new ShareFile.Api.Client.Requests.Query<AsyncOperation>(entity.Client);
		    sfApiQuery.Action("BulkApply");
            sfApiQuery.Uri(url);
            sfApiQuery.QueryString("folderId", folderId);
            sfApiQuery.QueryString("batchSize", batchSize);
            sfApiQuery.HttpMethod = "POST";	
		    return sfApiQuery;
        }
    }
}