// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using ShareFile.Api.Models;
using ShareFile.Api.Client;
using ShareFile.Api.Client.Requests;

namespace ShareFile.Api.Client.Entities
{
#if ShareFile
	public class UsersEntityInternal : UsersEntity
	{
		public UsersEntityInternal(ShareFileClient client)
			: base (client)
		{

		}

		/// <summary>
		/// Get User Security
		/// </summary>
		/// <remarks>
		/// Retrieve the user security record - current state of the user regarding
		/// security and password settings.
		/// </remarks>
		/// <param name="id"></param>
		/// <returns>
		/// the user security status
		/// </returns>
		public IQuery<UserSecurity> GetSecurity(string id)
		{
			var sfApiQuery = new ShareFile.Api.Client.Requests.Query<UserSecurity>(Client);
			sfApiQuery.From("Users");
			sfApiQuery.Action("Security");
			sfApiQuery.Ids(id);
			sfApiQuery.HttpMethod = "GET";
			return sfApiQuery;
		}

	}
#endif
}
