// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using ShareFile.Api.Models;
using ShareFile.Api.Client;
using ShareFile.Api.Client.Requests;
using ShareFile.Api.Client.Extensions;


namespace ShareFile.Api.Client.Entities
{
#if ShareFile

	public interface IStorageCentersEntityInternal : IEntityBase
	{
		/// <summary>
		/// Get Storage Center
		/// </summary>
		/// <param name="id"></param>
		/// <returns>
		/// A single Storage Center
		/// </returns>
		IQuery<StorageCenter> Get(string id);
		/// <summary>
		/// Patch Storage Center
		/// </summary>
		/// <example>
		/// {
		/// "ExternalAddress":"https://server/",
		/// "Version":"4.12.20",
		/// "HostName":"hostname" }
		/// </example>
		/// <param name="id"></param>
		/// <param name="sc"></param>
		/// <returns>
		/// Modified Storage Center
		/// </returns>
		IQuery<StorageCenter> Update(string id, StorageCenter sc);
		/// <summary>
		/// Delete Storage Center
		/// </summary>
		/// <param name="id"></param>
		IQuery Delete(string id);
		/// <summary>
		/// Get List of StorageCenters from Zone
		/// </summary>
		/// <remarks>
		/// Lists Storage Centers of a given Zone
		/// </remarks>
		/// <param name="id"></param>
		/// <returns>
		/// A list of Storage Centers associated with the provided zone
		/// </returns>
		IQuery<ODataFeed<StorageCenter>> GetByZone(string id);
		/// <summary>
		/// Create StorageCenter
		/// </summary>
		/// <example>
		/// {
		/// "ExternalAddress":"https://server/",
		/// "Version":"4.12.20",
		/// "HostName":"hostname"
		/// }
		/// </example>
		/// <remarks>
		/// Creates a new Storage Center associated with a specific zone
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="storageCenter"></param>
		/// <returns>
		/// The new storage center
		/// </returns>
		IQuery<StorageCenter> CreateByZone(string id, StorageCenter storageCenter);
		/// <summary>
		/// Update StorageCenter
		/// </summary>
		/// <example>
		/// {
		/// "ExternalAddress":"https://server/",
		/// "Version":"4.12.20",
		/// "HostName":"hostname"
		/// }
		/// </example>
		/// <remarks>
		/// Updates an existing Storage Center
		/// </remarks>
		/// <param name="zid"></param>
		/// <param name="scid"></param>
		/// <param name="storageCenter"></param>
		/// <returns>
		/// the modified storage center
		/// </returns>
		IQuery<StorageCenter> UpdateByZone(string zid, string scid, StorageCenter storageCenter);
		/// <summary>
		/// Delete StorageCenter
		/// </summary>
		/// <remarks>
		/// Removes an existing storage center
		/// </remarks>
		/// <param name="zid"></param>
		/// <param name="scid"></param>
		IQuery DeleteByZone(string zid, string scid);
		/// <summary>
		/// Get StorageCenter Metadata
		/// </summary>
		/// <remarks>
		/// Gets metadata associated with the specified storage center
		/// </remarks>
		/// <param name="zid"></param>
		/// <param name="scid"></param>
		/// <returns>
		/// the storage center metadata feed
		/// </returns>
		IQuery<ODataFeed<Metadata>> GetMetadata(string zid, string scid);
		/// <summary>
		/// Create or update StorageCenter Metadata
		/// </summary>
		/// <example>
		/// [
		/// {"Name":"metadataName1", "Value":"metadataValue1", "IsPublic":"true"},
		/// {"Name":"metadataName2", "Value":"metadataValue2", "IsPublic":"false"},
		/// ...
		/// ]
		/// </example>
		/// <remarks>
		/// Creates or updates Metadata entries associated with the specified storage center
		/// </remarks>
		/// <param name="zid"></param>
		/// <param name="scid"></param>
		/// <param name="metadata"></param>
		/// <returns>
		/// the storage center metadata feed
		/// </returns>
		IQuery<ODataFeed<Metadata>> CreateMetadata(string zid, string scid, IEnumerable<Metadata> metadata);
		/// <summary>
		/// Delete StorageCenter Metadata
		/// </summary>
		/// <remarks>
		/// Delete the Metadata entry associated with the specified storage center
		/// </remarks>
		/// <param name="zid"></param>
		/// <param name="scid"></param>
		/// <param name="name"></param>
		/// <returns>
		/// no data on success
		/// </returns>
		IQuery DeleteMetadata(string zid, string scid, string name);
	}

	public class StorageCentersEntityInternal : EntityBase, IStorageCentersEntityInternal
	{
		public StorageCentersEntityInternal(IShareFileClient client)
			: base (client, "StorageCenters")
			
		{

		}

		/// <summary>
		/// Get Storage Center
		/// </summary>
		/// <param name="id"></param>
		/// <returns>
		/// A single Storage Center
		/// </returns>
		public IQuery<StorageCenter> Get(string id)
		{
			var sfApiQuery = new ShareFile.Api.Client.Requests.Query<StorageCenter>(Client);
			sfApiQuery.From("StorageCenters");
			sfApiQuery.Ids(id);
			sfApiQuery.HttpMethod = "GET";
			return sfApiQuery;
		}

		/// <summary>
		/// Patch Storage Center
		/// </summary>
		/// <example>
		/// {
		/// "ExternalAddress":"https://server/",
		/// "Version":"4.12.20",
		/// "HostName":"hostname" }
		/// </example>
		/// <param name="id"></param>
		/// <param name="sc"></param>
		/// <returns>
		/// Modified Storage Center
		/// </returns>
		public IQuery<StorageCenter> Update(string id, StorageCenter sc)
		{
			var sfApiQuery = new ShareFile.Api.Client.Requests.Query<StorageCenter>(Client);
			sfApiQuery.From("StorageCenters");
			sfApiQuery.Ids(id);
			sfApiQuery.Body = sc;
			sfApiQuery.HttpMethod = "PATCH";
			return sfApiQuery;
		}

		/// <summary>
		/// Delete Storage Center
		/// </summary>
		/// <param name="id"></param>
		public IQuery Delete(string id)
		{
			var sfApiQuery = new ShareFile.Api.Client.Requests.Query(Client);
			sfApiQuery.From("StorageCenters");
			sfApiQuery.Ids(id);
			sfApiQuery.HttpMethod = "DELETE";
			return sfApiQuery;
		}

		/// <summary>
		/// Get List of StorageCenters from Zone
		/// </summary>
		/// <remarks>
		/// Lists Storage Centers of a given Zone
		/// </remarks>
		/// <param name="id"></param>
		/// <returns>
		/// A list of Storage Centers associated with the provided zone
		/// </returns>
		public IQuery<ODataFeed<StorageCenter>> GetByZone(string id)
		{
			var sfApiQuery = new ShareFile.Api.Client.Requests.Query<ODataFeed<StorageCenter>>(Client);
			sfApiQuery.From("Zones");
			sfApiQuery.Action("StorageCenters");
			sfApiQuery.Ids(id);
			sfApiQuery.HttpMethod = "GET";
			return sfApiQuery;
		}

		/// <summary>
		/// Create StorageCenter
		/// </summary>
		/// <example>
		/// {
		/// "ExternalAddress":"https://server/",
		/// "Version":"4.12.20",
		/// "HostName":"hostname"
		/// }
		/// </example>
		/// <remarks>
		/// Creates a new Storage Center associated with a specific zone
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="storageCenter"></param>
		/// <returns>
		/// The new storage center
		/// </returns>
		public IQuery<StorageCenter> CreateByZone(string id, StorageCenter storageCenter)
		{
			var sfApiQuery = new ShareFile.Api.Client.Requests.Query<StorageCenter>(Client);
			sfApiQuery.From("Zones");
			sfApiQuery.Action("StorageCenters");
			sfApiQuery.Ids(id);
			sfApiQuery.Body = storageCenter;
			sfApiQuery.HttpMethod = "POST";
			return sfApiQuery;
		}

		/// <summary>
		/// Update StorageCenter
		/// </summary>
		/// <example>
		/// {
		/// "ExternalAddress":"https://server/",
		/// "Version":"4.12.20",
		/// "HostName":"hostname"
		/// }
		/// </example>
		/// <remarks>
		/// Updates an existing Storage Center
		/// </remarks>
		/// <param name="zid"></param>
		/// <param name="scid"></param>
		/// <param name="storageCenter"></param>
		/// <returns>
		/// the modified storage center
		/// </returns>
		public IQuery<StorageCenter> UpdateByZone(string zid, string scid, StorageCenter storageCenter)
		{
			var sfApiQuery = new ShareFile.Api.Client.Requests.Query<StorageCenter>(Client);
			sfApiQuery.From("Zones");
			sfApiQuery.Action("StorageCenters");
			sfApiQuery.Ids(zid);
			sfApiQuery.ActionIds(scid);
			sfApiQuery.Body = storageCenter;
			sfApiQuery.HttpMethod = "PATCH";
			return sfApiQuery;
		}

		/// <summary>
		/// Delete StorageCenter
		/// </summary>
		/// <remarks>
		/// Removes an existing storage center
		/// </remarks>
		/// <param name="zid"></param>
		/// <param name="scid"></param>
		public IQuery DeleteByZone(string zid, string scid)
		{
			var sfApiQuery = new ShareFile.Api.Client.Requests.Query(Client);
			sfApiQuery.From("Zones");
			sfApiQuery.Action("StorageCenters");
			sfApiQuery.Ids(zid);
			sfApiQuery.ActionIds(scid);
			sfApiQuery.HttpMethod = "DELETE";
			return sfApiQuery;
		}

		/// <summary>
		/// Get StorageCenter Metadata
		/// </summary>
		/// <remarks>
		/// Gets metadata associated with the specified storage center
		/// </remarks>
		/// <param name="zid"></param>
		/// <param name="scid"></param>
		/// <returns>
		/// the storage center metadata feed
		/// </returns>
		public IQuery<ODataFeed<Metadata>> GetMetadata(string zid, string scid)
		{
			var sfApiQuery = new ShareFile.Api.Client.Requests.Query<ODataFeed<Metadata>>(Client);
			sfApiQuery.From("Zones");
			sfApiQuery.Action("StorageCenters");
			sfApiQuery.Ids(zid);
			sfApiQuery.ActionIds(scid);
			sfApiQuery.SubAction("Metadata");
			sfApiQuery.HttpMethod = "GET";
			return sfApiQuery;
		}

		/// <summary>
		/// Create or update StorageCenter Metadata
		/// </summary>
		/// <example>
		/// [
		/// {"Name":"metadataName1", "Value":"metadataValue1", "IsPublic":"true"},
		/// {"Name":"metadataName2", "Value":"metadataValue2", "IsPublic":"false"},
		/// ...
		/// ]
		/// </example>
		/// <remarks>
		/// Creates or updates Metadata entries associated with the specified storage center
		/// </remarks>
		/// <param name="zid"></param>
		/// <param name="scid"></param>
		/// <param name="metadata"></param>
		/// <returns>
		/// the storage center metadata feed
		/// </returns>
		public IQuery<ODataFeed<Metadata>> CreateMetadata(string zid, string scid, IEnumerable<Metadata> metadata)
		{
			var sfApiQuery = new ShareFile.Api.Client.Requests.Query<ODataFeed<Metadata>>(Client);
			sfApiQuery.From("Zones");
			sfApiQuery.Action("StorageCenters");
			sfApiQuery.Ids(zid);
			sfApiQuery.ActionIds(scid);
			sfApiQuery.SubAction("Metadata");
			sfApiQuery.Body = metadata;
			sfApiQuery.HttpMethod = "POST";
			return sfApiQuery;
		}

		/// <summary>
		/// Delete StorageCenter Metadata
		/// </summary>
		/// <remarks>
		/// Delete the Metadata entry associated with the specified storage center
		/// </remarks>
		/// <param name="zid"></param>
		/// <param name="scid"></param>
		/// <param name="name"></param>
		/// <returns>
		/// no data on success
		/// </returns>
		public IQuery DeleteMetadata(string zid, string scid, string name)
		{
			var sfApiQuery = new ShareFile.Api.Client.Requests.Query(Client);
			sfApiQuery.From("Zones");
			sfApiQuery.Action("StorageCenters");
			sfApiQuery.Ids(zid);
			sfApiQuery.ActionIds(scid);
			sfApiQuery.SubAction("Metadata");
			sfApiQuery.QueryString("name", name);
			sfApiQuery.HttpMethod = "DELETE";
			return sfApiQuery;
		}

	}
#endif
}
