// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using ShareFile.Api.Models;
using ShareFile.Api.Client;

namespace ShareFile.Api.Client
{
	public class FavoriteFoldersEntity : ODataEntityBase
	{
		/// <summary>
		/// Get List of FavoriteFolders
		/// </summary>
		/// <remarks>
		/// Retrieves the list of Favorite folders for a given user.
		/// </remarks>
		/// <param name="id"></param>
		/// <returns>
		/// A list of Favorite Folders specified by this user
		/// </returns>
		public IQuery<ODataFeed<FavoriteFolder>> GetByUser(string id)
		{
			IQuery<ODataFeed<FavoriteFolder>> query = new IQuery<ODataFeed<FavoriteFolder>>(Client);
			query.From("User");
			query.Ids(id);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get List of FavoriteFolders
		/// </summary>
		/// <remarks>
		/// Retrieves the list of Favorite folders for a given user.
		/// </remarks>
		/// <param name="id"></param>
		/// <returns>
		/// A list of Favorite Folders specified by this user
		/// </returns>
		public IQuery<FavoriteFolder> GetByUser(string id, string id)
		{
			IQuery<FavoriteFolder> query = new IQuery<FavoriteFolder>(Client);
			query.From("User");
			query.Action("FavoriteFolders");
			query.Ids(id);
			query.ActionIds(id);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get FavoriteFolder
		/// </summary>
		/// <remarks>
		/// Retrieve a single Favorite Folder from a give user
		/// </remarks>
		/// <param name="userid"></param>
		/// <param name="itemid"></param>
		/// <returns>
		/// The selected Favorite Folder
		/// </returns>
		public IQuery<FavoriteFolder> Get(string userid, string itemid)
		{
			IQuery<FavoriteFolder> query = new IQuery<FavoriteFolder>(Client);
			query.From("FavoriteFolders");
			query.Ids("userid", userid);
			query.Ids("itemid", itemid);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Create FavoriteFolder
		/// </summary>
		/// <example>
		/// {
		/// "Folder": { "Id":"fo96aec5-d637-4124-bcc9-c86fd7301e4d" }
		/// }
		/// </example>
		/// <remarks>
		/// Adds an existing folder to the list of favorites of a given user.
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="folder"></param>
		/// <param name="alias"></param>
		/// <returns>
		/// A new FavoriteFolder record
		/// </returns>
		public IQuery<FavoriteFolder> CreateByUser(string id, FavoriteFolder folder, string alias = "")
		{
			IQuery<FavoriteFolder> query = new IQuery<FavoriteFolder>(Client);
			query.From("User");
			query.Action("FavoriteFolders");
			query.Ids(id);
			query.QueryString("alias", alias);
			query.Body = folder;
			query.HttpMethod = "POST";
			return query;
		}

		/// <summary>
		/// Delete FavoriteFolder
		/// </summary>
		/// <remarks>
		/// Removes a favorite folder from a user's list.
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="itemid"></param>
		public IQuery Delete(string itemid,  id = )
		{
			IQuery query = new IQuery(Client);
			query.From("User");
			query.Action("FavoriteFolders");
			query.Ids(itemid);
			query.ActionIds(id);
			query.HttpMethod = "DELETE";
			return query;
		}

		public IQuery DeleteByUser(string userId, string itemId)
		{
			IQuery query = new IQuery(Client);
			query.From("User");
			query.Action("FavoriteFolders");
			query.Ids(userId);
			query.ActionIds(itemId);
			query.HttpMethod = "DELETE";
			return query;
		}

	}
}
