// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using ShareFile.Api.Models;
using ShareFile.Api.Client;

namespace ShareFile.Api.Client
{
	public class ItemsEntity : ODataEntityBase
	{
		/// <summary>
		/// Get List of Items
		/// </summary>
		/// <remarks>
		/// Retrieve the initial folder and files of the authenticated user.
		/// This method will return the user's root directory, using Item.GetRootFromWasabiPath("root").
		/// It will force expansion of the Children element, so first level of items under the root is also returned
		/// </remarks>
		/// <returns>
		/// a user's root directory and first level of children items
		/// </returns>
		public IQuery<Item> Get()
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get List of Items
		/// </summary>
		/// <remarks>
		/// Retrieve the initial folder and files of the authenticated user.
		/// This method will return the user's root directory, using Item.GetRootFromWasabiPath("root").
		/// It will force expansion of the Children element, so first level of items under the root is also returned
		/// </remarks>
		/// <returns>
		/// a user's root directory and first level of children items
		/// </returns>
		public IQuery<Item> Get(string id)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Ids(id);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get List of Items
		/// </summary>
		/// <remarks>
		/// Retrieve the initial folder and files of the authenticated user.
		/// This method will return the user's root directory, using Item.GetRootFromWasabiPath("root").
		/// It will force expansion of the Children element, so first level of items under the root is also returned
		/// </remarks>
		/// <returns>
		/// a user's root directory and first level of children items
		/// </returns>
		public IQuery<Item> Get(string id, TreeMode treeMode, string sourceId, string rootId = null, VRootType rootType = Account, bool canCreateRootFolder = false, bool fileBox = false)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Ids(id);
			query.QueryString("treeMode", treeMode);
			query.QueryString("sourceId", sourceId);
			query.QueryString("rootId", rootId);
			query.QueryString("rootType", rootType);
			query.QueryString("canCreateRootFolder", canCreateRootFolder);
			query.QueryString("fileBox", fileBox);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get Stream
		/// </summary>
		/// <remarks>
		/// Retrieves the versions of a given Stream.
		/// An Item represents a single version of a file system object. The stream identifies
		/// all versions of the same file system object. For example, when users upload or modify an existing file, a new Item
		/// is created with the same StreamID. All default Item enumerations return only the latest version of a given stream.
		/// Use this method to retrieve previous versions of a given stream
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="includeDeleted"></param>
		public IQuery<ODataFeed<Item>> Stream(string id, bool includeDeleted = false)
		{
			IQuery<ODataFeed<Item>> query = new IQuery<ODataFeed<Item>>(Client);
			query.From("Items");
			query.Action("Stream");
			query.Ids(id);
			query.QueryString("includeDeleted", includeDeleted);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get Item by Path
		/// </summary>
		/// <remarks>
		/// Retrieves an item from its path. The path is of format /foldername/foldername/filename
		/// This call may redirect the client to another API provider, if the path
		/// contains a symbolic link.
		/// </remarks>
		/// <param name="path"></param>
		/// <returns>
		/// An item identified by a path
		/// </returns>
		public IQuery<Item> ByPath(string path)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Action("ByPath");
			query.QueryString("path", path);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get Item by Path
		/// </summary>
		/// <remarks>
		/// Retrieves an item from its path. The path is of format /foldername/foldername/filename
		/// This call may redirect the client to another API provider, if the path
		/// contains a symbolic link.
		/// </remarks>
		/// <param name="path"></param>
		/// <returns>
		/// An item identified by a path
		/// </returns>
		public IQuery<Item> ByPath( id = , string parentid, string path)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Action("ByPath");
			query.Ids(id);
			query.QueryString("parentid", parentid);
			query.QueryString("path", path);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get Parent Item
		/// </summary>
		/// <remarks>
		/// Retrieves the Parent navigation property of a single Item.
		/// </remarks>
		/// <param name="id"></param>
		/// <returns>
		/// the Parent Item of the give object ID.
		/// </returns>
		public IQuery<Item> GetParent(string id)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Action("Parent");
			query.Ids(id);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get Children
		/// </summary>
		/// <remarks>
		/// Handler for the Children navigation property of a given Item.
		/// A 302 redirection is returned if the folder is a SymbolicLink. The redirection
		/// will enumerate the children of the remote connector
		/// </remarks>
		/// <param name="id"></param>
		/// <returns>
		/// the list of children under the given object ID
		/// </returns>
		public IQuery<Item> GetChildren(string id)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Action("Children");
			query.Ids(id);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get Folder Access Info
		/// </summary>
		/// <remarks>
		/// Returns the effective Access Controls for the current authenticated user for the
		/// selected folder - i.e., the resulting set of Access Controls for the Item/User context.This operation applies to Folders only, will return an error for other Item types.
		/// </remarks>
		/// <param name="id"></param>
		/// <returns>
		/// The Folder Access Control Information
		/// </returns>
		public IQuery<ItemInfo> GetInfo(string id)
		{
			IQuery<ItemInfo> query = new IQuery<ItemInfo>(Client);
			query.From("Items");
			query.Action("Info");
			query.Ids(id);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Download Item Content
		/// </summary>
		/// <remarks>
		/// Initiate the download operation for an item. It will return 302 redirection to the
		/// actual download link. For Folders, the download link will retrieve a ZIP archive
		/// with the contents of the Folder.
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="redirect"></param>
		/// <returns>
		/// the download link for the provided item content.
		/// </returns>
		public IQuery<DownloadSpecification> Download(string id, bool redirect = true)
		{
			IQuery<DownloadSpecification> query = new IQuery<DownloadSpecification>(Client);
			query.From("Items");
			query.Action("Download");
			query.Ids(id);
			query.QueryString("redirect", redirect);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Create Folder
		/// </summary>
		/// <example>
		/// {
		/// "Name":"Folder Name",
		/// "Description":"Description",
		/// "Zone":{ "Id":"z014766e-8e96-4615-86aa-57132a69843c" }
		/// }
		/// </example>
		/// <remarks>
		/// Creates a new Folder.
		/// The POST body must contain the serialized object.
		/// For top-level folders, use Items/Folder.
		/// The Zone object may only be provided for top-level folders. The Zone object must
		/// contain a zone ID.
		/// </remarks>
		/// <param name="parentid"></param>
		/// <param name="folder"></param>
		/// <param name="overwrite"></param>
		/// <param name="passthrough"></param>
		/// <returns>
		/// the new Folder
		/// </returns>
		public IQuery<Item> CreateFolder(string parentid, Folder folder, bool overwrite = false, bool passthrough = false)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Action("Folder");
			query.Ids(parentid);
			query.QueryString("overwrite", overwrite);
			query.QueryString("passthrough", passthrough);
			query.Body = folder;
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Create Note
		/// </summary>
		/// <example>
		/// {
		/// "Name":"Note Name",
		/// "Description":"Description"
		/// }
		/// </example>
		/// <remarks>
		/// Creates a new Note.
		/// </remarks>
		/// <param name="parentid"></param>
		/// <param name="note"></param>
		/// <returns>
		/// the new Note
		/// </returns>
		public IQuery<Item> CreateNote(string parentid, Note note)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Action("Note");
			query.Ids(parentid);
			query.Body = note;
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Create Link
		/// </summary>
		/// <example>
		/// {
		/// "Name":"Link Name",
		/// "Description":"Description",
		/// "Uri":"https://server/path"
		/// }
		/// </example>
		/// <remarks>
		/// Creates a new Link
		/// </remarks>
		/// <param name="parentid"></param>
		/// <param name="link"></param>
		/// <returns>
		/// the new Link
		/// </returns>
		public IQuery<Item> CreateLink(string parentid, Link link)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Action("Link");
			query.Ids(parentid);
			query.Body = link;
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Create SymbolicLink
		/// </summary>
		/// <example>
		/// {
		/// "Name":"Connection Name",
		/// "Description":"Description",
		/// "Link":"https://server/path"
		/// }
		/// {
		/// "FileName":"RemoteFileName",
		/// "Description":"Description",
		/// "Zone":{ "Id":"z014766e-8e96-4615-86aa-57132a69843c" }
		/// }
		/// </example>
		/// <remarks>
		/// Creates a Symbolic Link
		/// The body must contain either a "Link" parameter with a fully qualified URI; or use
		/// FileName + Zone to have sharefile.com attempt to convert the Connector path to an
		/// URI using a call to the Zone - using ShareFile Hash authentication mode. For active
		/// clients, it's recommended to make the convertion call to the Zone directly, using
		/// Items/ByPath=name, retriving the resulting URL, and calling this method with the
		/// Link parameter.SymbolicLinks must be created as top-level folders
		/// </remarks>
		/// <param name="parentid"></param>
		/// <param name="symlink"></param>
		/// <param name="overwrite"></param>
		/// <returns>
		/// the new SymbolicLink
		/// </returns>
		public IQuery<SymbolicLink> CreateSymbolicLink(string parentid, SymbolicLink symlink, bool overwrite = false)
		{
			IQuery<SymbolicLink> query = new IQuery<SymbolicLink>(Client);
			query.From("Items");
			query.Action("SymbolicLink");
			query.Ids(parentid);
			query.QueryString("overwrite", overwrite);
			query.Body = symlink;
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Update Item
		/// </summary>
		/// <example>
		/// {
		/// "Name":"Name",
		/// "FileName":"FileName",
		/// "Description":"Description",
		/// "ExpirationDate": "date",
		/// "Parent": { "Id": "parentid" },
		/// "Zone": { "Id": "zoneid" }
		/// }
		/// </example>
		/// <remarks>
		/// Updates an Item object
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="item"></param>
		/// <returns>
		/// A modified Item object. If the item Zone or Parent Zone is modified, then this
		/// method will return an Asynchronous operation record instead. Note: the parameters listed in the
		/// body of the request are the only parameters that can be updated through this call.
		/// </returns>
		public IQuery<ODataObject> Update(string id, Item item)
		{
			IQuery<ODataObject> query = new IQuery<ODataObject>(Client);
			query.From("Items");
			query.Ids(id);
			query.Body = item;
			query.HttpMethod = "PATCH";
			return query;
		}

		/// <summary>
		/// Update Link
		/// </summary>
		/// <example>
		/// {
		/// "Name":"Name",
		/// "Uri":"https://server/path",
		/// "Description":"Description",
		/// "Parent": { "Id": "parentid" },
		/// }
		/// </example>
		/// <remarks>
		/// Updates a Link object
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="link"></param>
		/// <param name="notify"></param>
		/// <returns>
		/// A modified Link object
		/// </returns>
		public IQuery<Item> UpdateLink(string id, Link link, bool notify = false)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Action("Link");
			query.Ids(id);
			query.QueryString("notify", notify);
			query.Body = link;
			query.HttpMethod = "PATCH";
			return query;
		}

		/// <summary>
		/// Update Note
		/// </summary>
		/// <example>
		/// {
		/// "Name":"Name",
		/// "Description":"Description",
		/// "Parent": { "Id": "parentid" },
		/// }
		/// </example>
		/// <remarks>
		/// Updates a Note object
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="note"></param>
		/// <param name="notify"></param>
		/// <returns>
		/// The modified Note object
		/// </returns>
		public IQuery<Item> UpdateNote(string id, Note note, bool notify = false)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Action("Note");
			query.Ids(id);
			query.QueryString("notify", notify);
			query.Body = note;
			query.HttpMethod = "PATCH";
			return query;
		}

		/// <summary>
		/// Update SymbolicLink
		/// </summary>
		/// <example>
		/// {
		/// "Name":"Name",
		/// "Description":"Description",
		/// "Link": "https://server/path"
		/// }
		/// </example>
		/// <remarks>
		/// Updates a Symbolic Link object
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="symlink"></param>
		/// <returns>
		/// The modified SymbolicLink object
		/// </returns>
		public IQuery<SymbolicLink> UpdateSymbolicLink(string id, SymbolicLink symlink)
		{
			IQuery<SymbolicLink> query = new IQuery<SymbolicLink>(Client);
			query.From("Items");
			query.Action("SymbolicLink");
			query.Ids(id);
			query.Body = symlink;
			query.HttpMethod = "PATCH";
			return query;
		}

		public IQuery Delete(string id, bool singleversion = false, bool forceSync = false)
		{
			IQuery query = new IQuery(Client);
			query.From("Items");
			query.Ids(id);
			query.QueryString("singleversion", singleversion);
			query.QueryString("forceSync", forceSync);
			query.HttpMethod = "PATCH";
			return query;
		}

		/// <summary>
		/// Delete Multiple Items
		/// </summary>
		/// <example>
		/// ["id1","id2",...]
		/// </example>
		/// <remarks>
		/// All items in bulk delete must be children of the same parent, identified in the URI
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="body"></param>
		public IQuery BulkDelete(string parentid, IEnumerable<string> ids, bool forceSync = false)
		{
			IQuery query = new IQuery(Client);
			query.From("Items");
			query.Action("BulkDelete");
			query.Ids(parentid);
			query.QueryString("ids", ids);
			query.QueryString("forceSync", forceSync);
			query.HttpMethod = "POST";
			return query;
		}

		/// <summary>
		/// Get Thumbnail
		/// </summary>
		/// <remarks>
		/// Retrieve a thumbnail link from the specified Item.
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="size"></param>
		/// <returns>
		/// A 302 redirection to the Thumbnail link
		/// </returns>
		public IQuery<Stream> GetThumbnail(string id, int size = 75)
		{
			IQuery<Stream> query = new IQuery<Stream>(Client);
			query.From("Items");
			query.Action("Thumbnail");
			query.Ids(id);
			query.QueryString("size", size);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get Breadcrumbs
		/// </summary>
		/// <remarks>
		/// Retrieves the path from an item from the root. The return list is a Feed of Items, with the top-level
		/// folder at the first position. If this item is in a Connection path, the breadcrumbs may contain URL
		/// reference back to the parent account - and the Item in the feed will contain just the URL reference.
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="path"></param>
		/// <param name="vroot"></param>
		/// <returns>
		/// A feed containing the path of folders from the specified root to the item, in order
		/// </returns>
		public IQuery<ODataFeed<Item>> GetBreadcrumbs(string id, string path = null, VRootType vroot = Default)
		{
			IQuery<ODataFeed<Item>> query = new IQuery<ODataFeed<Item>>(Client);
			query.From("Items");
			query.Action("Breadcrumbs");
			query.Ids(id);
			query.QueryString("path", path);
			query.QueryString("vroot", vroot);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Copy Item
		/// </summary>
		/// <remarks>
		/// Copies an item to a new target Folder. If the target folder is in another zone, the operation will
		/// return an AsyncOperation record instead. Clients may query the /AsyncOperation Entity to determine
		/// operation progress and result.
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="targetid"></param>
		/// <param name="overwrite"></param>
		/// <returns>
		/// the modified source object
		/// </returns>
		public IQuery<Item> Copy(string id, string targetid, bool overwrite = false)
		{
			IQuery<Item> query = new IQuery<Item>(Client);
			query.From("Items");
			query.Action("Copy");
			query.Ids(id);
			query.QueryString("targetid", targetid);
			query.QueryString("overwrite", overwrite);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Upload File
		/// </summary>
		/// <remarks>
		/// Prepares the links for uploading files to the target Folder.
		/// This method returns an Upload Specification object. The fields are
		/// populated based on the upload method, provider, and resume parameters passed to the
		/// upload call.
		/// The Method determines how the URLs must be called.
		/// 
		/// Standard uploads use a single HTTP POST message to the ChunkUri address provided in
		/// the response. All other fields will be empty. Standard uploads do not support Resume.
		/// 
		/// Streamed uploads use multiple HTTP POST calls to the ChunkUri address. The client must
		/// append the parameters index, offset and hash to the end of the ChunkUri address. Index
		/// is a sequential number representing the data block (zero-based); Offset represents the
		/// byte offset for the block; and hash contains the MD5 hash of the block. The last HTTP
		/// POST must also contain finish=true parameter.
		/// 
		/// Threaded uploads use multiple HTTP POST calls to ChunkUri, and can have a number of
		/// threads issuing blocks in parallel. Clients must append index, offset and hash to
		/// the end of ChunkUri, as explained in Streamed. After all chunks were sent, the client
		/// must call the FinishUri provided in this spec.
		/// 
		/// For all uploaders, the contents of the POST Body can either be "raw", if the "Raw" parameter
		/// was provided to the Uploader, or use MIME multi-part form encoding otherwise. Raw uploads
		/// simply put the block content in the POST body - Content-Length specifies the size. Multi-part
		/// form encoding has to pass the File as a Form parameter named "File1".
		/// 
		/// For streamed and threaded, if Resume options were provided to the Upload call, then the
		/// fields IsResume, ResumeIndex, ResumeOffset and ResumeFileHash MAY be populated. If they are,
		/// it indicates that the server has identified a partial upload with that specification, and is
		/// ready to resume on the provided parameters. The clients can then verify the ResumeFileHash to
		/// ensure the file has not been modified; and continue issuing ChunkUri calls from the ResumeIndex
		/// ResumeOffset parameters. If the client decides to restart, it should simply ignore the resume
		/// parameters and send the blocks from Index 0.
		/// 
		/// For all uploaders: the result code for the HTTP POST calls to Chunk and Finish Uri can either
		/// be a 401 - indicating authentication is required; 4xx/5xx indicating some kind of error; or
		/// 200 with a Content Body of format 'ERROR:message'. Successful calls will return either a 200
		/// response with no Body, or with Body of format 'OK'.
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="method"></param>
		/// <param name="raw"></param>
		/// <param name="fileName"></param>
		/// <param name="fileSize"></param>
		/// <param name="batchId"></param>
		/// <param name="batchLast"></param>
		/// <param name="canResume"></param>
		/// <param name="startOver"></param>
		/// <param name="unzip"></param>
		/// <param name="tool"></param>
		/// <param name="overwrite"></param>
		/// <param name="title"></param>
		/// <param name="details"></param>
		/// <param name="isSend"></param>
		/// <param name="sendGuid"></param>
		/// <param name="opid"></param>
		/// <param name="threadCount"></param>
		/// <param name="responseFormat"></param>
		/// <param name="notify"></param>
		/// <returns>
		/// an Upload Specification element, containing the links for uploading, and the parameters for resume.
		/// The caller must know the protocol for sending the prepare, chunk and finish URLs returned in the spec; as well as
		/// negotiate the resume upload.
		/// </returns>
		public IQuery<UploadSpecification> Upload(string id, UploadMethod method = Standard, bool raw = false, string fileName = null, long fileSize = 0, string batchId = null, bool batchLast = false, bool canResume = false, bool startOver = false, bool unzip = false, string tool = "apiv3", bool overwrite = false, string title = null, string details = null, bool isSend = false, string sendGuid = null, string opid = null, int threadCount = 4, string responseFormat = "json", bool notify = false, int? expirationDays = null)
		{
			IQuery<UploadSpecification> query = new IQuery<UploadSpecification>(Client);
			query.From("Items");
			query.Action("Upload");
			query.Ids(id);
			query.QueryString("method", method);
			query.QueryString("raw", raw);
			query.QueryString("fileName", fileName);
			query.QueryString("fileSize", fileSize);
			query.QueryString("batchId", batchId);
			query.QueryString("batchLast", batchLast);
			query.QueryString("canResume", canResume);
			query.QueryString("startOver", startOver);
			query.QueryString("unzip", unzip);
			query.QueryString("tool", tool);
			query.QueryString("overwrite", overwrite);
			query.QueryString("title", title);
			query.QueryString("details", details);
			query.QueryString("isSend", isSend);
			query.QueryString("sendGuid", sendGuid);
			query.QueryString("opid", opid);
			query.QueryString("threadCount", threadCount);
			query.QueryString("responseFormat", responseFormat);
			query.QueryString("notify", notify);
			query.QueryString("expirationDays", expirationDays);
			query.HttpMethod = "POST";
			return query;
		}

		/// <summary>
		/// Unlock File
		/// </summary>
		/// <remarks>
		/// Unlock a locked file.
		/// This operation is only implemented in Sharepoint providers (/sp)
		/// </remarks>
		/// <param name="id"></param>
		/// <param name="message"></param>
		public IQuery CheckIn(string id, string message)
		{
			IQuery query = new IQuery(Client);
			query.From("Items");
			query.Action("CheckIn");
			query.Ids(id);
			query.QueryString("message", message);
			query.HttpMethod = "POST";
			return query;
		}

		/// <summary>
		/// Lock File
		/// </summary>
		/// <remarks>
		/// Locks a file.
		/// This operation is only implemented in Sharepoint providers (/sp)
		/// </remarks>
		/// <param name="id"></param>
		public IQuery CheckOut(string id)
		{
			IQuery query = new IQuery(Client);
			query.From("Items");
			query.Action("CheckOut");
			query.Ids(id);
			query.HttpMethod = "POST";
			return query;
		}

		/// <summary>
		/// Search
		/// </summary>
		/// <remarks>
		/// Search for Items matching the criteria of the query parameter
		/// </remarks>
		/// <param name="query"></param>
		/// <returns>
		/// SearchResults
		/// </returns>
		public IQuery<SearchResults> Search(string query)
		{
			IQuery<SearchResults> query = new IQuery<SearchResults>(Client);
			query.From("Items");
			query.Action("Search");
			query.QueryString("query", query);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get all Item Protocol Link
		/// </summary>
		/// <remarks>
		/// This method returns all alternate protocol links supported by ShareFile (such
		/// as WOPI, FTP, WebDAV).
		/// </remarks>
		/// <param name="id"></param>
		/// <returns>
		/// A Feed containing all protocols links supported by the given item
		/// </returns>
		public IQuery<ODataFeed<ItemProtocolLink>> GetProtocolLinks(string parentid)
		{
			IQuery<ODataFeed<ItemProtocolLink>> query = new IQuery<ODataFeed<ItemProtocolLink>>(Client);
			query.From("Items");
			query.Action("ProtocolLinks");
			query.Ids(parentid);
			query.HttpMethod = "GET";
			return query;
		}

		/// <summary>
		/// Get all Item Protocol Link
		/// </summary>
		/// <remarks>
		/// This method returns all alternate protocol links supported by ShareFile (such
		/// as WOPI, FTP, WebDAV).
		/// </remarks>
		/// <param name="id"></param>
		/// <returns>
		/// A Feed containing all protocols links supported by the given item
		/// </returns>
		public IQuery<ItemProtocolLink> GetProtocolLinks(string parentid, string id)
		{
			IQuery<ItemProtocolLink> query = new IQuery<ItemProtocolLink>(Client);
			query.From("Items");
			query.Action("ProtocolLinks");
			query.Ids(parentid);
			query.ActionIds(id);
			query.HttpMethod = "GET";
			return query;
		}

	}
}
