// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace ShareFile.Api.Models 
{
	public class FreeTrialAccount : Account 
	{
		public string PromoCode { get; set; }

		public DateTime? EndDate { get; set; }

		public bool? IsValid { get; set; }

		public string ConversionType { get; set; }

		public bool? HasFollowedUp { get; set; }

		public DateTime? FollowUpDate { get; set; }

		public string CancellationReason { get; set; }

		public string SignupProcess { get; set; }

		public decimal? ConversionIndexDay7 { get; set; }

		public decimal? ConversionIndexDay14 { get; set; }

		public decimal? LTVIndex { get; set; }

		public string AllSources { get; set; }

		public string ReferralID { get; set; }

		public int? TrialTypeID { get; set; }

		public string InitialCallRepID { get; set; }

		public DateTime? InitialCallDate { get; set; }

		public int? DemoStatus { get; set; }

		public DateTime? DemoDate { get; set; }

		public string MarketoID { get; set; }

	}
}