// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace ShareFile.Api.Models 
{
	public class Query : ODataObject 
	{
		public IEnumerable<string> AuthIDs { get; set; }

		public IEnumerable<string> ItemTypes { get; set; }

		public IEnumerable<string> ParentID { get; set; }

		public IEnumerable<string> CreatorID { get; set; }

		public string LuceneQuery { get; set; }

		public string SearchQuery { get; set; }

		public string CreateStartDate { get; set; }

		public string CreateEndDate { get; set; }

		public bool ItemNameOnly { get; set; }

	}
}